<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-10-12T10:06:05 BDT" name="Default suite" finished-at="2025-10-12T10:06:47 BDT" duration-ms="42054">
    <groups>
    </groups>
    <test started-at="2025-10-12T10:06:05 BDT" name="Default test" finished-at="2025-10-12T10:06:47 BDT" duration-ms="42054">
      <class name="TestCases.CM_OrganizationCreateNew">
        <test-method is-config="true" signature="setup()[pri:0, instance:TestCases.CM_OrganizationCreateNew@5b218417]" started-at="2025-10-12T10:06:05 BDT" name="setup" finished-at="2025-10-12T10:06:12 BDT" duration-ms="7158" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="navigateToHomePage()[pri:0, instance:TestCases.CM_OrganizationCreateNew@5b218417]" started-at="2025-10-12T10:06:12 BDT" name="navigateToHomePage" finished-at="2025-10-12T10:06:23 BDT" duration-ms="10795" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateToHomePage -->
        <test-method signature="CM_Organization_CreateNew()[pri:1, instance:TestCases.CM_OrganizationCreateNew@5b218417]" started-at="2025-10-12T10:06:23 BDT" name="CM_Organization_CreateNew" finished-at="2025-10-12T10:06:46 BDT" duration-ms="23421" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to exception: Expected condition failed: waiting for element to be clickable: By.xpath: //a[contains(@href, 'organization') or contains(., 'Manage Organization')]//span (tried for 10 second(s) with 500 milliseconds interval)
Build info: version: '4.36.0', revision: '6d115cfd87'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.28'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 141.0.7390.67, chrome: {chromedriverVersion: 141.0.7390.76 (d6fcfbb51aac..., userDataDir: C:\Users\SIL_LA~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:12326}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:12326/devtoo..., se:cdpVersion: 141.0.7390.67, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 6aa562f5a404ae880350e8606502fdde]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to exception: Expected condition failed: waiting for element to be clickable: By.xpath: //a[contains(@href, 'organization') or contains(., 'Manage Organization')]//span (tried for 10 second(s) with 500 milliseconds interval)
Build info: version: '4.36.0', revision: '6d115cfd87'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.28'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 141.0.7390.67, chrome: {chromedriverVersion: 141.0.7390.76 (d6fcfbb51aac..., userDataDir: C:\Users\SIL_LA~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:12326}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:12326/devtoo..., se:cdpVersion: 141.0.7390.67, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 6aa562f5a404ae880350e8606502fdde
at org.testng.Assert.fail(Assert.java:111)
at TestCases.CM_OrganizationCreateNew.CM_Organization_CreateNew(CM_OrganizationCreateNew.java:183)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CM_Organization_CreateNew -->
        <test-method is-config="true" signature="captureFailureScreenshot(org.testng.ITestResult)[pri:0, instance:TestCases.CM_OrganizationCreateNew@5b218417]" started-at="2025-10-12T10:06:46 BDT" name="captureFailureScreenshot" finished-at="2025-10-12T10:06:47 BDT" duration-ms="174" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=CM_Organization_CreateNew status=FAILURE method=CM_OrganizationCreateNew.CM_Organization_CreateNew()[pri:1, instance:TestCases.CM_OrganizationCreateNew@5b218417] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureFailureScreenshot -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:TestCases.CM_OrganizationCreateNew@5b218417]" started-at="2025-10-12T10:06:47 BDT" name="teardown" finished-at="2025-10-12T10:06:47 BDT" duration-ms="472" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- TestCases.CM_OrganizationCreateNew -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
